### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by noPersonality** [Euronymou5/Doxxer-Toolkit#11]
### **Cant start the tool on ubuntu:**
Traceback (most recent call last):
  File "/home/username/Doxxer-Toolkit/dox_en.py", line 961, in <module>
    menu()
  File "/home/username/Doxxer-Toolkit/dox_en.py", line 893, in menu
    print(logo)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-12: ordinal not in range(256)

**Comment by Euronymou5** [comment]
> ### **Cant start the tool on ubuntu:**
> Traceback (most recent call last): File "/home/username/Doxxer-Toolkit/dox_en.py", line 961, in menu() File "/home/username/Doxxer-Toolkit/dox_en.py", line 893, in menu print(logo) UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-12: ordinal not in range(256)

Hello, sorry for responding a bit late. I added '# -- coding: utf-8 --' at the beginning of the script to prevent your system from attempting to use the latin-1 encoding. If the issue persists, please let me know.

**Comment by S3RG10XD** [comment]
i have the same problem, but it stil does not work

**Comment by S3RG10XD** [comment]
> > ### **Cant start the tool on ubuntu:**
> > Traceback (most recent call last): File "/home/username/Doxxer-Toolkit/dox_en.py", line 961, in menu() File "/home/username/Doxxer-Toolkit/dox_en.py", line 893, in menu print(logo) UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-12: ordinal not in range(256)
> 
> Hello, sorry for responding a bit late. I added '# -- coding: utf-8 --' at the beginning of the script to prevent your system from attempting to use the latin-1 encoding. If the issue persists, please let me know.

i have the same problem, but it stil does not work

**Comment by Euronymou5** [comment]
> > > ### **Cant start the tool on ubuntu:**
> > > Traceback (most recent call last): File "/home/username/Doxxer-Toolkit/dox_en.py", line 961, in menu() File "/home/username/Doxxer-Toolkit/dox_en.py", line 893, in menu print(logo) UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-12: ordinal not in range(256)
> > 
> > 
> > Hello, sorry for responding a bit late. I added '# -- coding: utf-8 --' at the beginning of the script to prevent your system from attempting to use the latin-1 encoding. If the issue persists, please let me know.
> 
> i have the same problem, but it stil does not work

it's possible that your systems are using 'Latin-1' as the default encoding, which causes it to try encoding characters in utf-8 format, resulting in the error. You could try changing the default encoding of your system to utf-8 and try again

**Comment by ChintuReddy8179** [comment]
> > > > ### **Cant start the tool on ubuntu:**
> > > > Traceback (most recent call last): File "/home/username/Doxxer-Toolkit/dox_en.py", line 961, in menu() File "/home/username/Doxxer-Toolkit/dox_en.py", line 893, in menu print(logo) UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-12: ordinal not in range(256)
> > > 
> > > 
> > > Hello, sorry for responding a bit late. I added '# -- coding: utf-8 --' at the beginning of the script to prevent your system from attempting to use the latin-1 encoding. If the issue persists, please let me know.
> > 
> > 
> > i have the same problem, but it stil does not work
> 
> it's possible that your systems are using 'Latin-1' as the default encoding, which causes it to try encoding characters in utf-8 format, resulting in the error. You could try changing the default encoding of your system to utf-8 and try again

I'm facing same error in termux please help
